#include <string.h>
#include "diksamc.h"

ErrorDefinition dkc_error_message_format[] = {
    {"dummy"},
    {"Syntax error (near $(token))."},
    {"Invalid character ($(bad_char))."},
    {"Function name is duplicated ($(name))."},
    {"Invalid multibyte character."},
    {"Unexpected wide string."},
    {"Elements of an array cannot be final."},
    {"Compound assignment operators cannot be applied to final."},
    {"Argument name $(name) is duplicated in function."},
    {"Variable name $(name) is duplicated."},
    {"Variable or function $(name) not found."},
    {"$(name) is a function name, but parentheses are missing for function call."},
    {"Cannot cast to or from derived type."},
    {"Cannot cast because $(src) does not implement $(dest)."},
    {"Invalid operand type for arithmetic operator."},
    {"Invalid operand type for comparison operator."},
    {"Invalid operand type for logical and/or operator."},
    {"Invalid operand type for negation operator."},
    {"Invalid operand type for logical not operator."},
    {"Invalid operand type for increment/decrement operator."},
    {"Operand for function call operator is not a function name."},
    {"Function $(name) not found."},
    {"Incorrect number of arguments for function."},
    {"Left-hand side of assignment operator is not an lvalue."},
    {"Label $(label) does not exist."},
    {"Array literal requires at least one element."},
    {"Left-hand side of subscript operator [] is not an array."},
    {"Subscript for array is not an integer."},
    {"Size of array is not an integer."},
    {"Dividing an integer value by zero."},
    {"Package name is too long (ridiculous!)."},
    {"Required file not found ($(file))."},
    {"An error occurred in require ($(status))."},
    {"The same package is required multiple times from a single source ($(package_name))."},
    {"Package specification is required for the name to be renamed with rename."},
    {"'abstract' is specified multiple times."},
    {"Access modifiers are specified multiple times."},
    {"'override' is specified multiple times."},
    {"'virtual' is specified multiple times."},
    {"The member operator cannot be applied to that type."},
    {"$(class_name) does not have a member named $(member_name)."},
    {"The member $(member_name) is private and cannot be accessed."},
    {"An abstract method cannot have an implementation."},
    {"A non-abstract method must have an implementation."},
    {"Inheriting from multiple classes ($(name) is the second class) is not allowed."},
    {"In Disam, only abstract classes can be inherited (class $(name) is not abstract)."},
    {"An abstract class ($(name)) is being instantiated with 'new'."},
    {"A function with 'void' type is returning a value."},
    {"Class $(name) was not found."},
    {"The member specified as a constructor ($(member_name)) is not a method."},
    {"The method specified in 'new' is not a constructor ($(member_name))."},
    {"The field ($(member_name)) cannot be called at the moment."},
    {"Trying to assign to a method ($(member_name))."},
    {"A non-virtual method ($(name)) cannot be overridden."},
    {"When overriding a method, 'override' specification is required ($(name))."},
    {"There is an abstract method $(method_name) in a non-abstract class."},
    {"'super' is used in a class that does not have a superclass."},
    {"'super' can only be used to call a method."},
    {"The field of 'super' cannot be referenced."},
    {"$(name) is a field. It cannot be overridden."},
    {"The field name $(name) is duplicated."},
    {"There is no method named $(name) for an array."},
    {"There is no method named $(name) for a string."},
    {"The operand of 'instanceof' must be a reference type."},
    {"The type of the right-hand operand of 'instanceof' must be a reference type."},
    {"The target of 'instanceof' must be a class."},
    {"This 'instanceof' always evaluates to true."},
    {"This 'instanceof' always evaluates to false."},
    {"There is no parent-child relationship in Diksam interfaces, so this 'instanceof' always evaluates to false."},
    {"Only classes can be the target of a downcast."},
    {"Only classes can be the destination of a downcast."},
    {"This downcast is unnecessary."},
    {"Trying to downcast to a superclass."},
    {"Trying to downcast to a class that is not in the inheritance hierarchy."},
    {"There is no parent-child relationship in Diksam interfaces, so downcasting is not possible."},
    {"Catching a non-class type."},
    {"The class $(class_name) being caught is not a subclass of Exception."},
    {"Throwing a non-class type."},
    {"The class $(class_name) being thrown is not a subclass of Exception."},
    {"There is a 'throw' statement outside of a 'catch' block with no operand."},
    {"The statement $(statement_name) cannot appear in a 'finally' block."},
    {"The name $(name) specified in 'throws' was not found."},
    {"The name $(name) specified in 'throws' is not a subclass of Exception."},
    {"The exception $(name) must be specified in a 'throws' clause or caught internally."},
    {"It is importing itself."},
    {"The condition of the 'if' statement is not of boolean type."},
    {"The condition of the 'while' statement is not of boolean type."},
    {"The condition of the 'for' statement is not of boolean type."},
    {"The condition of the 'do while' statement is not of boolean type."},
    {"The type of the expression in the 'case' statement does not match."},
    {"The variable $(name) is final and cannot be assigned a value."},
    {"The field $(name) is final and cannot be assigned a value."},
    {"The final variable $(name) has no initializer."},
    {"The access modifier of the overridden method $(name) is more restrictive than that of its superclass."},
    {"The number of arguments for the method or function $(name) is incorrect."},
    {"The type of the $(index)th parameter $(param_name) for method or function $(func_name) is incorrect."},
    {"The return type for method or function $(name) is invalid."},
    {"Method or function $(func_name) declares incompatible exception $(exception_name) in throws clause."},
    {"Constructors cannot be called directly."},
    {"Type name $(name) not found."},
    {"Enumeration type $(type_name) does not have enumerator $(enumerator_name)."},
    {"Interfaces cannot be inherited in Diksam (for now)."},
    {"Member $(member_name) cannot be accessed outside of the package."},
    {"Class $(class_name) cannot be accessed outside of the package."},
    {"'this' cannot be used outside of a class."},
    {"'super' cannot be used outside of a class."},
    {"The operand of the ~ operator must be an int."},
    {"The operands of a binary bitwise operator must be int or boolean."},
    {"File ended in the middle of a C-style comment."},
    {"File ended in the middle of a string literal."},
    {"Character literals must have only one character."},
    {"dummy"}
};
